### ISSUE TITLE
The `ALTER ROLE` syntax is not supported

### ISSUE THREAD

**Issue by r4ntix** [sqlparser-rs/sqlparser-rs#941]
# Background

The sqlparser-rs currently supported `role` syntax:
- [x] create role ✅ 
- [x] drop role ✅ 
- [x] set role ✅ 
- [ ] alter role

# Proposal

The syntax of PostgreSQL is as follows:
```sql
ALTER ROLE _`role_specification`_ [ WITH ] _`option`_ [ ... ]

where _`option`_ can be:

      SUPERUSER | NOSUPERUSER
    | CREATEDB | NOCREATEDB
    | CREATEROLE | NOCREATEROLE
    | INHERIT | NOINHERIT
    | LOGIN | NOLOGIN
    | REPLICATION | NOREPLICATION
    | BYPASSRLS | NOBYPASSRLS
    | CONNECTION LIMIT _`connlimit`_
    | [ ENCRYPTED ] PASSWORD '_`password`_' | PASSWORD NULL
    | VALID UNTIL '_`timestamp`_'

ALTER ROLE _`name`_ RENAME TO _`new_name`_

ALTER ROLE { _`role_specification`_ | ALL } [ IN DATABASE _`database_name`_ ] SET _`configuration_parameter`_ { TO | = } { _`value`_ | DEFAULT }
ALTER ROLE { _`role_specification`_ | ALL } [ IN DATABASE _`database_name`_ ] SET _`configuration_parameter`_ FROM CURRENT
ALTER ROLE { _`role_specification`_ | ALL } [ IN DATABASE _`database_name`_ ] RESET _`configuration_parameter`_
ALTER ROLE { _`role_specification`_ | ALL } [ IN DATABASE _`database_name`_ ] RESET ALL

where _`role_specification`_ can be:

    _`role_name`_
  | CURRENT_ROLE
  | CURRENT_USER
  | SESSION_USER
```

The syntax of MS SQL Server is as follows:
```sql
ALTER ROLE  role_name  
{  
       ADD MEMBER database_principal  
    |  DROP MEMBER database_principal  
    |  WITH NAME = new_name  
}  
[;]
```

# Implementation Plan

- [x] add `ALTER ROLE` syntax of PostgreSQL ✅ 
- [x] add `ALTER ROLE` syntax of MS SQL Server ✅ 
- [x] add parser tests ✅ 

# Addtional Context

Reference:
* [MySQL :: MySQL 8.0 Reference Manual :: 6.2.10 Using Roles](https://dev.mysql.com/doc/refman/8.0/en/roles.html)
* [MySQL :: MySQL 8.1 Reference Manual :: 13.7.1.1 ALTER USER Statement](https://dev.mysql.com/doc/refman/8.1/en/alter-user.html)
* [Support CREATE ROLE and DROP ROLE by blx · Pull Request #598 · sqlparser-rs/sqlparser-rs (github.com)](https://github.com/sqlparser-rs/sqlparser-rs/pull/598/files)
* [PostgreSQL: Documentation: 15: CREATE ROLE](https://www.postgresql.org/docs/current/sql-createrole.html)
* [PostgreSQL: Documentation: 15: ALTER ROLE](https://www.postgresql.org/docs/current/sql-alterrole.html)
* [ALTER ROLE (Transact-SQL) - SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-role-transact-sql?view=sql-server-ver16)
